# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50011742bb20298b6f28824a847ac506cd6c4da1563f16286a6f80209c2d61f9af24f2700789b420f69af19dbf461e1e26a39b90d6c15f555f32a8c4f5b34f07

test:
  secret_key_base: a2080cfe7398b2b9a620bda9d4a548b2dbaba1174559b9bd24f7905c5b23d34a4d08191e4da9d6c580eb4f9931a9b9d3a7dae66646ea2d0dee696aa0926ab2de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
